services:
  vault:
    image: hashicorp/vault:1.7.3
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - ./data:/vault/data
      - ./config.hcl:/vault/config/config.hcl
    cap_add:
      - IPC_LOCK

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./env/mongo.env
    volumes:
      - "./mongo/data:/mongo/data"
    networks:
      - mongodb

  mongodbtest:
    image: mongo
    command: mongod --port 27027
    ports:
      - "27027:27027"
    env_file:
      - ./env/mongo-test.env
    volumes:
      - "./mongo/data-test:/mongo/data-test"
    networks:
      - mongodbtest

  mongoimport:
    image: mongo
    volumes:
      - ./mongo/data/users.json:/src/data/users.json
    command: mongoimport --host mongo --username root --password pwd --port 27017 --db admin --collection userInfoEntity --file /src/data/users.json --jsonArray
    depends_on:
      - mongo
    networks:
      - mongodb

  order-search-service:
    build:
      context: ./order-search-service
      dockerfile: Dockerfile
    image: order-search-service
    volumes:
      - ./order-search-service/logs:/logs
    ports:
      - "8091:8091"
    env_file:
      - ./env/order-search-service.env
    networks:
      - mongodb
      - mongodbtest
      - network-default

  product-info-service:
    build:
      context: ./product-info-service
      dockerfile: Dockerfile
    image: product-info-service
    ports:
      - "8092:8092"
    env_file:
      - ./env/product-info-service.env
    networks:
      - mongodb
      - mongodbtest
      - network-default

  user-info-service:
    build:
      context: ./user-info-service
      dockerfile: Dockerfile
    image: user-info-service
    volumes:
      - ./user-info-service/logs:/logs
    ports:
      - "8093:8093"
    env_file:
      - ./env/user-info-service.env
    depends_on:
      - mongo
      - mongodbtest
      - order-search-service
      - product-info-service
    networks:
      - mongodb
      - mongodbtest
      - network-default

  logging-service:
    build:
      context: ./logging-service
      dockerfile: Dockerfile
    image: logging-service
    volumes:
      - ./logging-service/logs:/logs
    ports:
      - "8094:8094"
    env_file:
      - ./env/logging-service.env
    networks:
      - mongodb
      - mongodbtest
      - network-default

networks:
  mongodb:
  mongodbtest:
  network-default:
