services:
  vault:
    image: hashicorp/vault:1.7.3
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - ./data:/vault/data
      - ./config.hcl:/vault/config/config.hcl
    cap_add:
      - IPC_LOCK

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./env/mongo.env

  mongoimport:
    image: mongo
    volumes:
      - ./mongo/data/users.json:/src/data/users.json
    command: mongoimport --host mongo --username root --password pwd --db admin --collection userInfoEntity --file /src/data/users.json --jsonArray

  order-search-service:
    build:
      context: ./order-search-service
      dockerfile: Dockerfile
    image: order-search-service
    ports:
      - "8091:8091"
    env_file:
      - ./env/order-search-service.env

  product-info-service:
    build:
      context: ./product-info-service
      dockerfile: Dockerfile
    image: product-info-service
    ports:
      - "8092:8092"
    env_file:
      - ./env/product-info-service.env

  user-info-service:
    build:
      context: ./user-info-service
      dockerfile: Dockerfile
    image: user-info-service
    ports:
      - "8093:8093"
    env_file:
      - ./env/user-info-service.env
    depends_on:
      - mongo
      - order-search-service
      - product-info-service
