package com.user.info.util;

public class TestConstants {

	public static final String ORDER_SEARCH_SERVICE_RESPONSE_91987654321 = "\r\n"
			+ "	{\r\n"
			+ "		\"phoneNumber\": \"91987654321\",\r\n"
			+ "		\"orderNumber\": \"Order_0\",\r\n"
			+ "		\"productCode\": \"3852\"\r\n"
			+ "	}\r\n"
			+ "	{\r\n"
			+ "		\"phoneNumber\": \"91987654321\",\r\n"
			+ "		\"orderNumber\": \"Order_1\",\r\n"
			+ "		\"productCode\": \"5256\"\r\n"
			+ "	}\r\n"
			+ "	{\r\n"
			+ "		\"phoneNumber\": \"91987654321\",\r\n"
			+ "		\"orderNumber\": \"Order_2\",\r\n"
			+ "		\"productCode\": \"7894\"\r\n"
			+ "	}\r\n"
			+ "	{\r\n"
			+ "		\"phoneNumber\": \"91987654321\",\r\n"
			+ "		\"orderNumber\": \"Order_3\",\r\n"
			+ "		\"productCode\": \"9822\"\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "";
	
	public static final String ORDER_SEARCH_SERVICE_RESPONSE_91897654321 = "{\r\n"
			+ "    \"phoneNumber\": \"91897654321\",\r\n"
			+ "    \"orderNumber\": \"Order_0\",\r\n"
			+ "    \"productCode\": \"3852\"\r\n"
			+ "}\r\n"
			+ "{\r\n"
			+ "    \"phoneNumber\": \"91897654321\",\r\n"
			+ "    \"orderNumber\": \"Order_1\",\r\n"
			+ "    \"productCode\": \"5256\"\r\n"
			+ "}\r\n"
			+ "{\r\n"
			+ "    \"phoneNumber\": \"91897654321\",\r\n"
			+ "    \"orderNumber\": \"Order_2\",\r\n"
			+ "    \"productCode\": \"7894\"\r\n"
			+ "}\r\n"
			+ "{\r\n"
			+ "    \"phoneNumber\": \"91897654321\",\r\n"
			+ "    \"orderNumber\": \"Order_3\",\r\n"
			+ "    \"productCode\": \"9822\"\r\n"
			+ "}";
			
	public static final String PRODUCT_INFO_SERVICE_RESPONSE_3852 = "[\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"111\",\r\n"
			+ "        \"productCode\": \"3852\",\r\n"
			+ "        \"productName\": \"IceCream\",\r\n"
			+ "        \"score\": 9753.78\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"222\",\r\n"
			+ "        \"productCode\": \"3852\",\r\n"
			+ "        \"productName\": \"Milk\",\r\n"
			+ "        \"score\": 4605.54\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"333\",\r\n"
			+ "        \"productCode\": \"3852\",\r\n"
			+ "        \"productName\": \"Meal\",\r\n"
			+ "        \"score\": 5963.03\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"444\",\r\n"
			+ "        \"productCode\": \"3852\",\r\n"
			+ "        \"productName\": \"Apple\",\r\n"
			+ "        \"score\": 3177.27\r\n"
			+ "    }\r\n"
			+ "]\r\n"
			+ "";
	public static final String PRODUCT_INFO_SERVICE_RESPONSE_5256 = "[\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"111\",\r\n"
			+ "        \"productCode\": \"5256\",\r\n"
			+ "        \"productName\": \"IceCream\",\r\n"
			+ "        \"score\": 493.38\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"222\",\r\n"
			+ "        \"productCode\": \"5256\",\r\n"
			+ "        \"productName\": \"Milk\",\r\n"
			+ "        \"score\": 1910.15\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"333\",\r\n"
			+ "        \"productCode\": \"5256\",\r\n"
			+ "        \"productName\": \"Meal\",\r\n"
			+ "        \"score\": 2824.19\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"444\",\r\n"
			+ "        \"productCode\": \"5256\",\r\n"
			+ "        \"productName\": \"Apple\",\r\n"
			+ "        \"score\": 1525.5\r\n"
			+ "    }\r\n"
			+ "]\r\n"
			+ "";
	public static final String PRODUCT_INFO_SERVICE_RESPONSE_7894 = "[\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"111\",\r\n"
			+ "        \"productCode\": \"7894\",\r\n"
			+ "        \"productName\": \"IceCream\",\r\n"
			+ "        \"score\": 4498.26\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"222\",\r\n"
			+ "        \"productCode\": \"7894\",\r\n"
			+ "        \"productName\": \"Milk\",\r\n"
			+ "        \"score\": 5796.52\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"333\",\r\n"
			+ "        \"productCode\": \"7894\",\r\n"
			+ "        \"productName\": \"Meal\",\r\n"
			+ "        \"score\": 3059.57\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"444\",\r\n"
			+ "        \"productCode\": \"7894\",\r\n"
			+ "        \"productName\": \"Apple\",\r\n"
			+ "        \"score\": 5876.35\r\n"
			+ "    }\r\n"
			+ "]\r\n"
			+ "";
	public static final String PRODUCT_INFO_SERVICE_RESPONSE_9822 = "[\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"111\",\r\n"
			+ "        \"productCode\": \"9822\",\r\n"
			+ "        \"productName\": \"IceCream\",\r\n"
			+ "        \"score\": 3083.18\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"222\",\r\n"
			+ "        \"productCode\": \"9822\",\r\n"
			+ "        \"productName\": \"Milk\",\r\n"
			+ "        \"score\": 2683.11\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"333\",\r\n"
			+ "        \"productCode\": \"9822\",\r\n"
			+ "        \"productName\": \"Meal\",\r\n"
			+ "        \"score\": 5719.11\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"productId\": \"444\",\r\n"
			+ "        \"productCode\": \"9822\",\r\n"
			+ "        \"productName\": \"Apple\",\r\n"
			+ "        \"score\": 9818.82\r\n"
			+ "    }\r\n"
			+ "]\r\n"
			+ "";
}
